### PR TITLE
Adding LED board

### PR DESCRIPTION
**Pull request by samsonfsb**
Maybe just a quick check on this @sinistra92

### CODE REVIEW

**Comment by sinistra92** [comment]
There is a resistor missing for one of the LEDs;
You didn't add resistor value;
the PCB could be a lot smaller, do you have the LED placement driven by other design? Otherwise maybe you could put them in line and make PCB narrower?
Other than that - perfecto. nice little one. :+1:

**Comment by samsonfsb** [comment]
Doy! That's what you get for trying to smash stuff out to quickly!

The LED without a resistor is okay as the resistor is already on the MVP PCB.

LED placement is driven by feedback from Naomi when she said that she had trouble differentiating status LEDs and Power meter LEDs. Want to get them as far away as possible from each other as possible without going larger tha 50mmx50mm which is the smallest (and cheapest) PCB you can get made by Seeedstudio.

**Comment by sinistra92** [comment]
awesome, ha, good. Looks good for merge.

**Comment by samsonfsb** [comment]
Merged

**Pull request merged**
